services:
  backend:
    build: ./backend
    devices:
      - /dev/irrigation_relay:/dev/irrigation_relay
    volumes:
      - type: bind
        source: /srv/irrigation-controller/data
        target: /data
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
